return PlaceObj('ModDef', {
	'title', "Green Mars Terraforming Lightmodel",
	'description', 'Covers mars terrain and atmosphere with greenish bioluminescent microbiotic life.\nEffect can be toggled using "Green Mars Toggle" hotkey (Ctrl-Alt-Shift-K by default).',
	'image', "thumb.png",
	'last_changes', "Wrap all DoneObject stuff in error handling.",
	'id', "mk-fg/green-mars-terraforming-lightmodel",
	'steam_id', "1543384888",
	'author', "mk-fg",
	'version', 3,
	'lua_revision', LuaRevision,
	'code', {"Code/green-mars-terraforming-lightmodel.lua"},
	'saved', 1540148465,
	'screenshot1', "Images/gmtl-shot-1.png",
	'screenshot2', "Images/gmtl-shot-2.png",
	'screenshot3', "Images/gmtl-shot-3.png",
	'screenshot4', "Images/gmtl-shot-4.png",
	'screenshot5', "Images/gmtl-shot-5.png",
	'TagLightmodels', true,
})
