return PlaceObj('ModDef', {
	'title', "Green Mars Terraforming Lightmodel",
	'description', "Covers mars terrain and atmosphere with greenish bioluminescent microbiotic life.",
	'image', "thumb.png",
	'last_changes', "Initial release.",
	'id', "mk-fg/green-mars-terraforming-lightmodel",
	'steam_id', "1543384888",
	'author', "mk-fg",
	'version', 2,
	'lua_revision', 235636,
	'code', {"Code/green-mars-terraforming-lightmodel.lua"},
	'saved', 1540031231,
	'screenshot1', "Images/gmtl-shot-1.png",
	'screenshot2', "Images/gmtl-shot-2.png",
	'screenshot3', "Images/gmtl-shot-3.png",
	'screenshot4', "Images/gmtl-shot-4.png",
	'screenshot5', "Images/gmtl-shot-5.png",
	'TagLightmodels', true,
})