return PlaceObj('ModDef', {
	'title', "Disable Maintenance button",
	'description', "Adds button to toggle whether drones will patch building up when maintenance is required.\nUnmaintained building will keep working until it finally breaks down.\nDisabling/enabling maintenance mode should have immediate effect on drones, stopping ones that are en-route if necessary.",
	'image', "thumb.png",
	'last_changes', "Fix issue with buildings never getting repaired when maintenance was disabled when drone was underway.",
	'id', "mk-fg/disable-maintenance-button",
	'steam_id', "1541524054",
	'author', "mk-fg",
	'version', 5,
	'lua_revision', 245618,
	'code', {"Code/disable-maintenance-button.lua"},
	'saved', 1543087443,
	'TagInterface', true,
	'TagTools', true,
})
