return PlaceObj('ModDef', {
	'title', "Disable Maintenance button",
	'description', "Adds button to toggle whether drones will patch building up when maintenance is required.\nUnmaintained building will keep working until it finally breaks down.\nDisabling/enabling maintenance mode should have immediate effect on drones, stopping ones that are en-route if necessary.",
	'image', "thumb.png",
	'last_changes', "Wrap all DoneObject stuff in error handling.",
	'id', "mk-fg/disable-maintenance-button",
	'steam_id', "1541524054",
	'author', "mk-fg",
	'version', 4,
	'lua_revision', LuaRevision,
	'code', {"Code/disable-maintenance-button.lua"},
	'saved', 1541142996,
	'TagInterface', true,
	'TagTools', true,
})
