local conf = require('config')

data:extend{
	{ order = '01',
		setting_type = 'startup',
		name = 'bds-signal-update-interval',
		type = 'int-setting',
		minimum_value = 1,
		default_value = conf.ticks_between_updates },
	{ order = '02',
		setting_type = 'startup',
		name = 'bds-signal-update-steps',
		type = 'int-setting',
		minimum_value = 1,
		default_value = conf.ticks_update_steps },
	{ order = '03',
		setting_type = 'startup',
		name = 'bds-default-scan-range',
		type = 'int-setting',
		minimum_value = 1,
		default_value = conf.default_scan_range },
	{ order = '04',
		setting_type = 'startup',
		name = 'bds-max-scan-range',
		type = 'int-setting',
		minimum_value = conf.default_scan_range,
		default_value = conf.max_scan_range },
	{ order = '05',
		setting_type = 'startup',
		name = 'bds-scan-other',
		type = 'bool-setting',
		default_value = conf.scan_other },
}
