local conf = require('config')

data:extend{

	{ order = '0010',
		setting_type = 'runtime-global',
		name = 'wisps-can-attack',
		type = 'bool-setting',
		default_value = not conf.peaceful_wisps },
	{ order = '0020',
		setting_type = 'runtime-global',
		name = 'defences-shoot-wisps',
		type = 'bool-setting',
		default_value = not conf.peaceful_defences },
	{ order = '0030',
		setting_type = 'runtime-global',
		name = 'purple-wisp-damage',
		type = 'bool-setting',
		default_value = not conf.peaceful_spores },

	{ order = '0110',
		setting_type = 'runtime-global',
		name = 'wisp-map-spawn-count',
		type = 'int-setting',
		minimum_value = 0,
		default_value = conf.wisp_max_count },

	{ order = '0120',
		setting_type = 'runtime-global',
		name = 'wisp-map-spawn-purple',
		type = 'double-setting',
		minimum_value = 0,
		maximum_value = 1.0,
		default_value = conf.wisp_forest_spawn_chance_purple },
	{ order = '0130',
		setting_type = 'runtime-global',
		name = 'wisp-map-spawn-yellow',
		type = 'double-setting',
		minimum_value = 0,
		maximum_value = 1.0,
		default_value = conf.wisp_forest_spawn_chance_yellow },
	{ order = '0140',
		setting_type = 'runtime-global',
		name = 'wisp-map-spawn-red',
		type = 'double-setting',
		minimum_value = 0,
		maximum_value = 1.0,
		default_value = conf.wisp_forest_spawn_chance_red },

}
