data:extend{
	{ order = '01',
		name = 'cclp-add-extra-colors',
		type = 'bool-setting',
		setting_type = 'startup',
		default_value = true },
	{ order = '02',
		name = 'cclp-light-radius',
		type = 'double-setting',
		minimum_value = 0,
		setting_type = 'startup',
		default_value = 6 },
	{ order = '03',
		name = 'cclp-light-intensity',
		type = 'double-setting',
		minimum_value = 0,
		maximum_value = 1.0,
		setting_type = 'startup',
		default_value = 0.9 },
	{ order = '04',
		name = 'cclp-color-intensity',
		type = 'double-setting',
		minimum_value = 0,
		maximum_value = 1.0,
		setting_type = 'startup',
		default_value = 0.135 },
}
